
export const city = [
    {"id":"1","state_id":"2","city_name":"Nicobar"},
    {"id":"2","state_id":"2","city_name":"North and Middle Andaman"},
    {"id":"3","state_id":"2","city_name":"South Andaman"},
    {"id":"4","state_id":"3","city_name":"Anantapur"},
    {"id":"5","state_id":"3","city_name":"Chittoor"},
    {"id":"6","state_id":"3","city_name":"East Godavari"},
    {"id":"7","state_id":"3","city_name":"Guntur"},
    {"id":"8","state_id":"3","city_name":"Krishna"},
    {"id":"9","state_id":"3","city_name":"Kurnool"},
    {"id":"10","state_id":"3","city_name":"Prakasam"},
    {"id":"11","state_id":"3","city_name":"Srikakulam"},
    {"id":"12","state_id":"3","city_name":"Sri Potti Sriramulu Nellore"},
    {"id":"13","state_id":"3","city_name":"Visakhapatnam"},
    {"id":"14","state_id":"3","city_name":"Vizianagaram"},
    {"id":"15","state_id":"3","city_name":"West Godavari"},
    {"id":"16","state_id":"3","city_name":"YSR District, Kadapa (Cuddapah)"},
    {"id":"17","state_id":"4","city_name":"Anjaw"},
    {"id":"18","state_id":"4","city_name":"Changlang"},
    {"id":"19","state_id":"4","city_name":"Dibang Valley"},
    {"id":"20","state_id":"4","city_name":"East Kameng"},
    {"id":"21","state_id":"4","city_name":"East Siang"},
    {"id":"22","state_id":"4","city_name":"Kamle"},
    {"id":"23","state_id":"4","city_name":"Kra Daadi"},
    {"id":"24","state_id":"4","city_name":"Kurung Kumey"},
    {"id":"25","state_id":"4","city_name":"Lepa Rada"},
    {"id":"26","state_id":"4","city_name":"Lohit"},
    {"id":"27","state_id":"4","city_name":"Longding"},
    {"id":"28","state_id":"4","city_name":"Lower Dibang Valley"},
    {"id":"29","state_id":"4","city_name":"Lower Siang"},
    {"id":"30","state_id":"4","city_name":"Lower Subansiri"},
    {"id":"31","state_id":"4","city_name":"Namsai"},
    {"id":"32","state_id":"4","city_name":"Pakke Kessang"},
    {"id":"33","state_id":"4","city_name":"Papum Pare"},
    {"id":"34","state_id":"4","city_name":"Shi Yomi"},
    {"id":"35","state_id":"4","city_name":"Siang"},
    {"id":"36","state_id":"4","city_name":"Tawang"},
    {"id":"37","state_id":"4","city_name":"Tirap"},
    {"id":"38","state_id":"4","city_name":"Upper Siang"},
    {"id":"39","state_id":"4","city_name":"Upper Subansiri"},
    {"id":"40","state_id":"4","city_name":"West Kameng"},
    {"id":"41","state_id":"4","city_name":"West Siang"},
    {"id":"42","state_id":"5","city_name":"Baksa"},
    {"id":"43","state_id":"5","city_name":"Barpeta"},
    {"id":"44","state_id":"5","city_name":"Biswanath"},
    {"id":"45","state_id":"5","city_name":"Bongaigaon"},
    {"id":"46","state_id":"5","city_name":"Cachar"},
    {"id":"47","state_id":"5","city_name":"Charaideo"},
    {"id":"48","state_id":"5","city_name":"Chirang"},
    {"id":"49","state_id":"5","city_name":"Darrang"},
    {"id":"50","state_id":"5","city_name":"Dhemaji"},
    {"id":"51","state_id":"5","city_name":"Dhubri"},
    {"id":"52","state_id":"5","city_name":"Dibrugarh"},
    {"id":"53","state_id":"5","city_name":"Dima Hasao (North Cachar Hills)"},
    {"id":"54","state_id":"5","city_name":"Goalpara"},
    {"id":"55","state_id":"5","city_name":"Golaghat"},
    {"id":"56","state_id":"5","city_name":"Hailakandi"},
    {"id":"57","state_id":"5","city_name":"Hojai"},
    {"id":"58","state_id":"5","city_name":"Jorhat"},
    {"id":"59","state_id":"5","city_name":"Kamrup"},
    {"id":"60","state_id":"5","city_name":"Kamrup Metropolitan"},
    {"id":"61","state_id":"5","city_name":"Karbi Anglong"},
    {"id":"62","state_id":"5","city_name":"Karimganj"},
    {"id":"63","state_id":"5","city_name":"Kokrajhar"},
    {"id":"64","state_id":"5","city_name":"Lakhimpur"},
    {"id":"65","state_id":"5","city_name":"Majuli"},
    {"id":"66","state_id":"5","city_name":"Morigaon"},
    {"id":"67","state_id":"5","city_name":"Nagaon"},
    {"id":"68","state_id":"5","city_name":"Nalbari"},
    {"id":"69","state_id":"5","city_name":"Sivasagar"},
    {"id":"70","state_id":"5","city_name":"Sonitpur"},
    {"id":"71","state_id":"5","city_name":"South Salamara-Mankachar"},
    {"id":"72","state_id":"5","city_name":"Tinsukia"},
    {"id":"73","state_id":"5","city_name":"Udalguri"},
    {"id":"74","state_id":"5","city_name":"West Karbi Anglong"},
    {"id":"75","state_id":"6","city_name":"Araria"},
    {"id":"76","state_id":"6","city_name":"Arwal"},
    {"id":"77","state_id":"6","city_name":"Aurangabad"},
    {"id":"78","state_id":"6","city_name":"Banka"},
    {"id":"79","state_id":"6","city_name":"Begusarai"},
    {"id":"80","state_id":"6","city_name":"Bhagalpur"},
    {"id":"81","state_id":"6","city_name":"Bhojpur"},
    {"id":"82","state_id":"6","city_name":"Buxar"},
    {"id":"83","state_id":"6","city_name":"Darbhanga"},
    {"id":"84","state_id":"6","city_name":"East Champaran (Motihari)"},
    {"id":"85","state_id":"6","city_name":"Gaya"},
    {"id":"86","state_id":"6","city_name":"Gopalganj"},
    {"id":"87","state_id":"6","city_name":"Jamui"},
    {"id":"88","state_id":"6","city_name":"Jehanabad"},
    {"id":"89","state_id":"6","city_name":"Kaimur (Bhabua)"},
    {"id":"90","state_id":"6","city_name":"Katihar"},
    {"id":"91","state_id":"6","city_name":"Khagaria"},
    {"id":"92","state_id":"6","city_name":"Kishanganj"},
    {"id":"93","state_id":"6","city_name":"Lakhisarai"},
    {"id":"94","state_id":"6","city_name":"Madhepura"},
    {"id":"95","state_id":"6","city_name":"Madhubani"},
    {"id":"96","state_id":"6","city_name":"Munger (Monghyr)"},
    {"id":"97","state_id":"6","city_name":"Muzaffarpur"},
    {"id":"98","state_id":"6","city_name":"Nalanda"},
    {"id":"99","state_id":"6","city_name":"Nawada"},
    {"id":"100","state_id":"6","city_name":"Patna"},
    {"id":"101","state_id":"6","city_name":"Purnia (Purnea)"},
    {"id":"102","state_id":"6","city_name":"Rohtas"},
    {"id":"103","state_id":"6","city_name":"Saharsa"},
    {"id":"104","state_id":"6","city_name":"Samastipur"},
    {"id":"105","state_id":"6","city_name":"Saran"},
    {"id":"106","state_id":"6","city_name":"Sheikhpura"},
    {"id":"107","state_id":"6","city_name":"Sheohar"},
    {"id":"108","state_id":"6","city_name":"Sitamarhi"},
    {"id":"109","state_id":"6","city_name":"Siwan"},
    {"id":"110","state_id":"6","city_name":"Supaul"},
    {"id":"111","state_id":"6","city_name":"Vaishali"},
    {"id":"112","state_id":"6","city_name":"West Champaran"},
    {"id":"113","state_id":"7","city_name":"Chandigarh"},
    {"id":"114","state_id":"8","city_name":"Balod"},
    {"id":"115","state_id":"8","city_name":"Baloda Bazar"},
    {"id":"116","state_id":"8","city_name":"Balrampur"},
    {"id":"117","state_id":"8","city_name":"Bastar"},
    {"id":"118","state_id":"8","city_name":"Bemetara"},
    {"id":"119","state_id":"8","city_name":"Bijapur"},
    {"id":"120","state_id":"8","city_name":"Bilaspur"},
    {"id":"121","state_id":"8","city_name":"Dantewada (South Bastar)"},
    {"id":"122","state_id":"8","city_name":"Dhamtari"},
    {"id":"123","state_id":"8","city_name":"Durg"},
    {"id":"124","state_id":"8","city_name":"Gariyaband"},
    {"id":"125","state_id":"8","city_name":"Janjgir-Champa"},
    {"id":"126","state_id":"8","city_name":"Jashpur"},
    {"id":"127","state_id":"8","city_name":"Kabirdham (Kawardha)"},
    {"id":"128","state_id":"8","city_name":"Kanker (North Bastar)"},
    {"id":"129","state_id":"8","city_name":"Kondagaon"},
    {"id":"130","state_id":"8","city_name":"Korba"},
    {"id":"131","state_id":"8","city_name":"Korea (Koriya)"},
    {"id":"132","state_id":"8","city_name":"Mahasamund"},
    {"id":"133","state_id":"8","city_name":"Mungeli"},
    {"id":"134","state_id":"8","city_name":"Narayanpur"},
    {"id":"135","state_id":"8","city_name":"Raigarh"},
    {"id":"136","state_id":"8","city_name":"Raipur"},
    {"id":"137","state_id":"8","city_name":"Rajnandgaon"},
    {"id":"138","state_id":"8","city_name":"Sukma"},
    {"id":"139","state_id":"8","city_name":"Surajpur"},
    {"id":"140","state_id":"8","city_name":"Surguja"},
    {"id":"141","state_id":"9","city_name":"Dadra & Nagar Haveli"},
    {"id":"142","state_id":"10","city_name":"Daman"},
    {"id":"143","state_id":"10","city_name":"Diu"},
    {"id":"144","state_id":"11","city_name":"Central Delhi"},
    {"id":"145","state_id":"11","city_name":"East Delhi"},
    {"id":"146","state_id":"11","city_name":"New Delhi"},
    {"id":"147","state_id":"11","city_name":"North Delhi"},
    {"id":"148","state_id":"11","city_name":"North East Delhi"},
    {"id":"149","state_id":"11","city_name":"North West Delhi"},
    {"id":"150","state_id":"11","city_name":"Shahdara"},
    {"id":"151","state_id":"11","city_name":"South Delhi"},
    {"id":"152","state_id":"11","city_name":"South East Delhi"},
    {"id":"153","state_id":"11","city_name":"South West Delhi"},
    {"id":"154","state_id":"11","city_name":"West Delhi"},
    {"id":"155","state_id":"12","city_name":"North Goa"},
    {"id":"156","state_id":"12","city_name":"South Goa"},
    {"id":"157","state_id":"13","city_name":"Ahmedabad"},
    {"id":"158","state_id":"13","city_name":"Amreli"},
    {"id":"159","state_id":"13","city_name":"Anand"},
    {"id":"160","state_id":"13","city_name":"Aravalli"},
    {"id":"161","state_id":"13","city_name":"Banaskantha (Palanpur)"},
    {"id":"162","state_id":"13","city_name":"Bharuch"},
    {"id":"163","state_id":"13","city_name":"Bhavnagar"},
    {"id":"164","state_id":"13","city_name":"Botad"},
    {"id":"165","state_id":"13","city_name":"Chhota Udepur"},
    {"id":"166","state_id":"13","city_name":"Dahod"},
    {"id":"167","state_id":"13","city_name":"Dangs (Ahwa)"},
    {"id":"168","state_id":"13","city_name":"Devbhoomi Dwarka"},
    {"id":"169","state_id":"13","city_name":"Gandhinagar"},
    {"id":"170","state_id":"13","city_name":"Gir Somnath"},
    {"id":"171","state_id":"13","city_name":"Jamnagar"},
    {"id":"172","state_id":"13","city_name":"Junagadh"},
    {"id":"173","state_id":"13","city_name":"Kachchh"},
    {"id":"174","state_id":"13","city_name":"Kheda (Nadiad)"},
    {"id":"175","state_id":"13","city_name":"Mahisagar"},
    {"id":"176","state_id":"13","city_name":"Mehsana"},
    {"id":"177","state_id":"13","city_name":"Morbi"},
    {"id":"178","state_id":"13","city_name":"Narmada (Rajpipla)"},
    {"id":"179","state_id":"13","city_name":"Navsari"},
    {"id":"180","state_id":"13","city_name":"Panchmahal (Godhra)"},
    {"id":"181","state_id":"13","city_name":"Patan"},
    {"id":"182","state_id":"13","city_name":"Porbandar"},
    {"id":"183","state_id":"13","city_name":"Rajkot"},
    {"id":"184","state_id":"13","city_name":"Sabarkantha (Himmatnagar)"},
    {"id":"185","state_id":"13","city_name":"Surat"},
    {"id":"186","state_id":"13","city_name":"Surendranagar"},
    {"id":"187","state_id":"13","city_name":"Tapi (Vyara)"},
    {"id":"188","state_id":"13","city_name":"Vadodara"},
    {"id":"189","state_id":"13","city_name":"Valsad"},
    {"id":"190","state_id":"14","city_name":"Ambala"},
    {"id":"191","state_id":"14","city_name":"Bhiwani"},
    {"id":"192","state_id":"14","city_name":"Charkhi Dadri"},
    {"id":"193","state_id":"14","city_name":"Faridabad"},
    {"id":"194","state_id":"14","city_name":"Fatehabad"},
    {"id":"195","state_id":"14","city_name":"Gurugram (Gurgaon)"},
    {"id":"196","state_id":"14","city_name":"Hisar"},
    {"id":"197","state_id":"14","city_name":"Jhajjar"},
    {"id":"198","state_id":"14","city_name":"Jind"},
    {"id":"199","state_id":"14","city_name":"Kaithal"},
    {"id":"200","state_id":"14","city_name":"Karnal"},
    {"id":"201","state_id":"14","city_name":"Kurukshetra"},
    {"id":"202","state_id":"14","city_name":"Mahendragarh"},
    {"id":"203","state_id":"14","city_name":"Nuh"},
    {"id":"204","state_id":"14","city_name":"Palwal"},
    {"id":"205","state_id":"14","city_name":"Panchkula"},
    {"id":"206","state_id":"14","city_name":"Panipat"},
    {"id":"207","state_id":"14","city_name":"Rewari"},
    {"id":"208","state_id":"14","city_name":"Rohtak"},
    {"id":"209","state_id":"14","city_name":"Sirsa"},
    {"id":"210","state_id":"14","city_name":"Sonipat"},
    {"id":"211","state_id":"14","city_name":"Yamunanagar"},
    {"id":"212","state_id":"15","city_name":"Bilaspur"},
    {"id":"213","state_id":"15","city_name":"Chamba"},
    {"id":"214","state_id":"15","city_name":"Hamirpur"},
    {"id":"215","state_id":"15","city_name":"Kangra"},
    {"id":"216","state_id":"15","city_name":"Kinnaur"},
    {"id":"217","state_id":"15","city_name":"Kullu"},
    {"id":"218","state_id":"15","city_name":"Lahaul & Spiti"},
    {"id":"219","state_id":"15","city_name":"Mandi"},
    {"id":"220","state_id":"15","city_name":"Shimla"},
    {"id":"221","state_id":"15","city_name":"Sirmaur (Sirmour)"},
    {"id":"222","state_id":"15","city_name":"Solan"},
    {"id":"223","state_id":"15","city_name":"Una"},
    {"id":"224","state_id":"16","city_name":"Anantnag"},
    {"id":"225","state_id":"16","city_name":"Bandipore"},
    {"id":"226","state_id":"16","city_name":"Baramulla"},
    {"id":"227","state_id":"16","city_name":"Budgam"},
    {"id":"228","state_id":"16","city_name":"Doda"},
    {"id":"229","state_id":"16","city_name":"Ganderbal"},
    {"id":"230","state_id":"16","city_name":"Jammu"},
    {"id":"231","state_id":"16","city_name":"Kathua"},
    {"id":"232","state_id":"16","city_name":"Kishtwar"},
    {"id":"233","state_id":"16","city_name":"Kulgam"},
    {"id":"234","state_id":"16","city_name":"Kupwara"},
    {"id":"235","state_id":"16","city_name":"Poonch"},
    {"id":"236","state_id":"16","city_name":"Pulwama"},
    {"id":"237","state_id":"16","city_name":"Rajouri"},
    {"id":"238","state_id":"16","city_name":"Ramban"},
    {"id":"239","state_id":"16","city_name":"Reasi"},
    {"id":"240","state_id":"16","city_name":"Samba"},
    {"id":"241","state_id":"16","city_name":"Shopian"},
    {"id":"242","state_id":"16","city_name":"Srinagar"},
    {"id":"243","state_id":"16","city_name":"Udhampur"},
    {"id":"244","state_id":"17","city_name":"Bokaro"},
    {"id":"245","state_id":"17","city_name":"Chatra"},
    {"id":"246","state_id":"17","city_name":"Deoghar"},
    {"id":"247","state_id":"17","city_name":"Dhanbad"},
    {"id":"248","state_id":"17","city_name":"Dumka"},
    {"id":"249","state_id":"17","city_name":"East Singhbhum"},
    {"id":"250","state_id":"17","city_name":"Garhwa"},
    {"id":"251","state_id":"17","city_name":"Giridih"},
    {"id":"252","state_id":"17","city_name":"Godda"},
    {"id":"253","state_id":"17","city_name":"Gumla"},
    {"id":"254","state_id":"17","city_name":"Hazaribag"},
    {"id":"255","state_id":"17","city_name":"Jamtara"},
    {"id":"256","state_id":"17","city_name":"Khunti"},
    {"id":"257","state_id":"17","city_name":"Koderma"},
    {"id":"258","state_id":"17","city_name":"Latehar"},
    {"id":"259","state_id":"17","city_name":"Lohardaga"},
    {"id":"260","state_id":"17","city_name":"Pakur"},
    {"id":"261","state_id":"17","city_name":"Palamu"},
    {"id":"262","state_id":"17","city_name":"Ramgarh"},
    {"id":"263","state_id":"17","city_name":"Ranchi"},
    {"id":"264","state_id":"17","city_name":"Sahibganj"},
    {"id":"265","state_id":"17","city_name":"Seraikela-Kharsawan"},
    {"id":"266","state_id":"17","city_name":"Simdega"},
    {"id":"267","state_id":"17","city_name":"West Singhbhum"},
    {"id":"268","state_id":"18","city_name":"Bagalkot"},
    {"id":"269","state_id":"18","city_name":"Ballari (Bellary)"},
    {"id":"270","state_id":"18","city_name":"Belagavi (Belgaum)"},
    {"id":"271","state_id":"18","city_name":"Bengaluru (Bangalore) Rural"},
    {"id":"272","state_id":"18","city_name":"Bengaluru (Bangalore) Urban"},
    {"id":"273","state_id":"18","city_name":"Bidar"},
    {"id":"274","state_id":"18","city_name":"Chamarajanagar"},
    {"id":"275","state_id":"18","city_name":"Chikballapur"},
    {"id":"276","state_id":"18","city_name":"Chikkamagaluru (Chikmagalur)"},
    {"id":"277","state_id":"18","city_name":"Chitradurga"},
    {"id":"278","state_id":"18","city_name":"Dakshina Kannada"},
    {"id":"279","state_id":"18","city_name":"Davangere"},
    {"id":"280","state_id":"18","city_name":"Dharwad"},
    {"id":"281","state_id":"18","city_name":"Gadag"},
    {"id":"282","state_id":"18","city_name":"Hassan"},
    {"id":"283","state_id":"18","city_name":"Haveri"},
    {"id":"284","state_id":"18","city_name":"Kalaburagi (Gulbarga)"},
    {"id":"285","state_id":"18","city_name":"Kodagu"},
    {"id":"286","state_id":"18","city_name":"Kolar"},
    {"id":"287","state_id":"18","city_name":"Koppal"},
    {"id":"288","state_id":"18","city_name":"Mandya"},
    {"id":"289","state_id":"18","city_name":"Mysuru (Mysore)"},
    {"id":"290","state_id":"18","city_name":"Raichur"},
    {"id":"291","state_id":"18","city_name":"Ramanagara"},
    {"id":"292","state_id":"18","city_name":"Shivamogga (Shimoga)"},
    {"id":"293","state_id":"18","city_name":"Tumakuru (Tumkur)"},
    {"id":"294","state_id":"18","city_name":"Udupi"},
    {"id":"295","state_id":"18","city_name":"Uttara Kannada (Karwar)"},
    {"id":"296","state_id":"18","city_name":"Vijayapura (Bijapur)"},
    {"id":"297","state_id":"18","city_name":"Yadgir"},
    {"id":"298","state_id":"19","city_name":"Alappuzha"},
    {"id":"299","state_id":"19","city_name":"Ernakulam"},
    {"id":"300","state_id":"19","city_name":"Idukki"},
    {"id":"301","state_id":"19","city_name":"Kannur"},
    {"id":"302","state_id":"19","city_name":"Kasaragod"},
    {"id":"303","state_id":"19","city_name":"Kollam"},
    {"id":"304","state_id":"19","city_name":"Kottayam"},
    {"id":"305","state_id":"19","city_name":"Kozhikode"},
    {"id":"306","state_id":"19","city_name":"Malappuram"},
    {"id":"307","state_id":"19","city_name":"Palakkad"},
    {"id":"308","state_id":"19","city_name":"Pathanamthitta"},
    {"id":"309","state_id":"19","city_name":"Thiruvananthapuram"},
    {"id":"310","state_id":"19","city_name":"Thrissur"},
    {"id":"311","state_id":"19","city_name":"Wayanad"},
    {"id":"312","state_id":"20","city_name":"Kargil"},
    {"id":"313","state_id":"20","city_name":"Leh"},
    {"id":"314","state_id":"21","city_name":"Lakshadweep"},
    {"id":"315","state_id":"22","city_name":"Agar Malwa"},
    {"id":"316","state_id":"22","city_name":"Alirajpur"},
    {"id":"317","state_id":"22","city_name":"Anuppur"},
    {"id":"318","state_id":"22","city_name":"Ashoknagar"},
    {"id":"319","state_id":"22","city_name":"Balaghat"},
    {"id":"320","state_id":"22","city_name":"Barwani"},
    {"id":"321","state_id":"22","city_name":"Betul"},
    {"id":"322","state_id":"22","city_name":"Bhind"},
    {"id":"323","state_id":"22","city_name":"Bhopal"},
    {"id":"324","state_id":"22","city_name":"Burhanpur"},
    {"id":"325","state_id":"22","city_name":"Chhatarpur"},
    {"id":"326","state_id":"22","city_name":"Chhindwara"},
    {"id":"327","state_id":"22","city_name":"Damoh"},
    {"id":"328","state_id":"22","city_name":"Datia"},
    {"id":"329","state_id":"22","city_name":"Dewas"},
    {"id":"330","state_id":"22","city_name":"Dhar"},
    {"id":"331","state_id":"22","city_name":"Dindori"},
    {"id":"332","state_id":"22","city_name":"Guna"},
    {"id":"333","state_id":"22","city_name":"Gwalior"},
    {"id":"334","state_id":"22","city_name":"Harda"},
    {"id":"335","state_id":"22","city_name":"Hoshangabad"},
    {"id":"336","state_id":"22","city_name":"Indore"},
    {"id":"337","state_id":"22","city_name":"Jabalpur"},
    {"id":"338","state_id":"22","city_name":"Jhabua"},
    {"id":"339","state_id":"22","city_name":"Katni"},
    {"id":"340","state_id":"22","city_name":"Khandwa"},
    {"id":"341","state_id":"22","city_name":"Khargone"},
    {"id":"342","state_id":"22","city_name":"Mandla"},
    {"id":"343","state_id":"22","city_name":"Mandsaur"},
    {"id":"344","state_id":"22","city_name":"Morena"},
    {"id":"345","state_id":"22","city_name":"Narsinghpur"},
    {"id":"346","state_id":"22","city_name":"Neemuch"},
    {"id":"347","state_id":"22","city_name":"Panna"},
    {"id":"348","state_id":"22","city_name":"Raisen"},
    {"id":"349","state_id":"22","city_name":"Rajgarh"},
    {"id":"350","state_id":"22","city_name":"Ratlam"},
    {"id":"351","state_id":"22","city_name":"Rewa"},
    {"id":"352","state_id":"22","city_name":"Sagar"},
    {"id":"353","state_id":"22","city_name":"Satna"},
    {"id":"354","state_id":"22","city_name":"Sehore"},
    {"id":"355","state_id":"22","city_name":"Seoni"},
    {"id":"356","state_id":"22","city_name":"Shahdol"},
    {"id":"357","state_id":"22","city_name":"Shajapur"},
    {"id":"358","state_id":"22","city_name":"Sheopur"},
    {"id":"359","state_id":"22","city_name":"Shivpuri"},
    {"id":"360","state_id":"22","city_name":"Sidhi"},
    {"id":"361","state_id":"22","city_name":"Singrauli"},
    {"id":"362","state_id":"22","city_name":"Tikamgarh"},
    {"id":"363","state_id":"22","city_name":"Ujjain"},
    {"id":"364","state_id":"22","city_name":"Umaria"},
    {"id":"365","state_id":"22","city_name":"Vidisha"},
    {"id":"366","state_id":"23","city_name":"Ahmednagar"},
    {"id":"367","state_id":"23","city_name":"Akola"},
    {"id":"368","state_id":"23","city_name":"Amravati"},
    {"id":"369","state_id":"23","city_name":"Aurangabad"},
    {"id":"370","state_id":"23","city_name":"Beed"},
    {"id":"371","state_id":"23","city_name":"Bhandara"},
    {"id":"372","state_id":"23","city_name":"Buldhana"},
    {"id":"373","state_id":"23","city_name":"Chandrapur"},
    {"id":"374","state_id":"23","city_name":"Dhule"},
    {"id":"375","state_id":"23","city_name":"Gadchiroli"},
    {"id":"376","state_id":"23","city_name":"Gondia"},
    {"id":"377","state_id":"23","city_name":"Hingoli"},
    {"id":"378","state_id":"23","city_name":"Jalgaon"},
    {"id":"379","state_id":"23","city_name":"Jalna"},
    {"id":"380","state_id":"23","city_name":"Kolhapur"},
    {"id":"381","state_id":"23","city_name":"Latur"},
    {"id":"382","state_id":"23","city_name":"Mumbai City"},
    {"id":"383","state_id":"23","city_name":"Mumbai Suburban"},
    {"id":"384","state_id":"23","city_name":"Nagpur"},
    {"id":"385","state_id":"23","city_name":"Nanded"},
    {"id":"386","state_id":"23","city_name":"Nandurbar"},
    {"id":"387","state_id":"23","city_name":"Nashik"},
    {"id":"388","state_id":"23","city_name":"Osmanabad"},
    {"id":"389","state_id":"23","city_name":"Palghar"},
    {"id":"390","state_id":"23","city_name":"Parbhani"},
    {"id":"391","state_id":"23","city_name":"Pune"},
    {"id":"392","state_id":"23","city_name":"Raigad"},
    {"id":"393","state_id":"23","city_name":"Ratnagiri"},
    {"id":"394","state_id":"23","city_name":"Sangli"},
    {"id":"395","state_id":"23","city_name":"Satara"},
    {"id":"396","state_id":"23","city_name":"Sindhudurg"},
    {"id":"397","state_id":"23","city_name":"Solapur"},
    {"id":"398","state_id":"23","city_name":"Thane"},
    {"id":"399","state_id":"23","city_name":"Wardha"},
    {"id":"400","state_id":"23","city_name":"Washim"},
    {"id":"401","state_id":"23","city_name":"Yavatmal"},
    {"id":"402","state_id":"24","city_name":"Bishnupur"},
    {"id":"403","state_id":"24","city_name":"Chandel"},
    {"id":"404","state_id":"24","city_name":"Churachandpur"},
    {"id":"405","state_id":"24","city_name":"Imphal East"},
    {"id":"406","state_id":"24","city_name":"Imphal West"},
    {"id":"407","state_id":"24","city_name":"Jiribam"},
    {"id":"408","state_id":"24","city_name":"Kakching"},
    {"id":"409","state_id":"24","city_name":"Kamjong"},
    {"id":"410","state_id":"24","city_name":"Kangpokpi"},
    {"id":"411","state_id":"24","city_name":"Noney"},
    {"id":"412","state_id":"24","city_name":"Pherzawl"},
    {"id":"413","state_id":"24","city_name":"Senapati"},
    {"id":"414","state_id":"24","city_name":"Tamenglong"},
    {"id":"415","state_id":"24","city_name":"Tengnoupal"},
    {"id":"416","state_id":"24","city_name":"Thoubal"},
    {"id":"417","state_id":"24","city_name":"Ukhrul"},
    {"id":"418","state_id":"25","city_name":"East Garo Hills"},
    {"id":"419","state_id":"25","city_name":"East Jaintia Hills"},
    {"id":"420","state_id":"25","city_name":"East Khasi Hills"},
    {"id":"421","state_id":"25","city_name":"North Garo Hills"},
    {"id":"422","state_id":"25","city_name":"Ri Bhoi"},
    {"id":"423","state_id":"25","city_name":"South Garo Hills"},
    {"id":"424","state_id":"25","city_name":"South West Garo Hills"},
    {"id":"425","state_id":"25","city_name":"South West Khasi Hills"},
    {"id":"426","state_id":"25","city_name":"West Garo Hills"},
    {"id":"427","state_id":"25","city_name":"West Jaintia Hills"},
    {"id":"428","state_id":"25","city_name":"West Khasi Hills"},
    {"id":"429","state_id":"26","city_name":"Aizawl"},
    {"id":"430","state_id":"26","city_name":"Champhai"},
    {"id":"431","state_id":"26","city_name":"Kolasib"},
    {"id":"432","state_id":"26","city_name":"Lawngtlai"},
    {"id":"433","state_id":"26","city_name":"Lunglei"},
    {"id":"434","state_id":"26","city_name":"Mamit"},
    {"id":"435","state_id":"26","city_name":"Saiha"},
    {"id":"436","state_id":"26","city_name":"Serchhip"},
    {"id":"437","state_id":"27","city_name":"Dimapur"},
    {"id":"438","state_id":"27","city_name":"Kiphire"},
    {"id":"439","state_id":"27","city_name":"Kohima"},
    {"id":"440","state_id":"27","city_name":"Longleng"},
    {"id":"441","state_id":"27","city_name":"Mokokchung"},
    {"id":"442","state_id":"27","city_name":"Mon"},
    {"id":"443","state_id":"27","city_name":"Peren"},
    {"id":"444","state_id":"27","city_name":"Phek"},
    {"id":"445","state_id":"27","city_name":"Tuensang"},
    {"id":"446","state_id":"27","city_name":"Wokha"},
    {"id":"447","state_id":"27","city_name":"Zunheboto"},
    {"id":"448","state_id":"28","city_name":"Angul"},
    {"id":"449","state_id":"28","city_name":"Balangir"},
    {"id":"450","state_id":"28","city_name":"Balasore"},
    {"id":"451","state_id":"28","city_name":"Bargarh"},
    {"id":"452","state_id":"28","city_name":"Bhadrak"},
    {"id":"453","state_id":"28","city_name":"Boudh"},
    {"id":"454","state_id":"28","city_name":"Cuttack"},
    {"id":"455","state_id":"28","city_name":"Deogarh"},
    {"id":"456","state_id":"28","city_name":"Dhenkanal"},
    {"id":"457","state_id":"28","city_name":"Gajapati"},
    {"id":"458","state_id":"28","city_name":"Ganjam"},
    {"id":"459","state_id":"28","city_name":"Jagatsinghapur"},
    {"id":"460","state_id":"28","city_name":"Jajpur"},
    {"id":"461","state_id":"28","city_name":"Jharsuguda"},
    {"id":"462","state_id":"28","city_name":"Kalahandi"},
    {"id":"463","state_id":"28","city_name":"Kandhamal"},
    {"id":"464","state_id":"28","city_name":"Kendrapara"},
    {"id":"465","state_id":"28","city_name":"Kendujhar (Keonjhar)"},
    {"id":"466","state_id":"28","city_name":"Khordha"},
    {"id":"467","state_id":"28","city_name":"Koraput"},
    {"id":"468","state_id":"28","city_name":"Malkangiri"},
    {"id":"469","state_id":"28","city_name":"Mayurbhanj"},
    {"id":"470","state_id":"28","city_name":"Nabarangpur"},
    {"id":"471","state_id":"28","city_name":"Nayagarh"},
    {"id":"472","state_id":"28","city_name":"Nuapada"},
    {"id":"473","state_id":"28","city_name":"Puri"},
    {"id":"474","state_id":"28","city_name":"Rayagada"},
    {"id":"475","state_id":"28","city_name":"Sambalpur"},
    {"id":"476","state_id":"28","city_name":"Sonepur"},
    {"id":"477","state_id":"28","city_name":"Sundargarh"},
    {"id":"478","state_id":"29","city_name":"Karaikal"},
    {"id":"479","state_id":"29","city_name":"Mahe"},
    {"id":"480","state_id":"29","city_name":"Puducherry"},
    {"id":"481","state_id":"29","city_name":"Yanam"},
    {"id":"482","state_id":"30","city_name":"Amritsar"},
    {"id":"483","state_id":"30","city_name":"Barnala"},
    {"id":"484","state_id":"30","city_name":"Bathinda"},
    {"id":"485","state_id":"30","city_name":"Faridkot"},
    {"id":"486","state_id":"30","city_name":"Fatehgarh Sahib"},
    {"id":"487","state_id":"30","city_name":"Fazilka"},
    {"id":"488","state_id":"30","city_name":"Ferozepur"},
    {"id":"489","state_id":"30","city_name":"Gurdaspur"},
    {"id":"490","state_id":"30","city_name":"Hoshiarpur"},
    {"id":"491","state_id":"30","city_name":"Jalandhar"},
    {"id":"492","state_id":"30","city_name":"Kapurthala"},
    {"id":"493","state_id":"30","city_name":"Ludhiana"},
    {"id":"494","state_id":"30","city_name":"Mansa"},
    {"id":"495","state_id":"30","city_name":"Moga"},
    {"id":"496","state_id":"30","city_name":"Muktsar"},
    {"id":"497","state_id":"30","city_name":"Nawanshahr (Shahid Bhagat Singh Nagar)"},
    {"id":"498","state_id":"30","city_name":"Pathankot"},
    {"id":"499","state_id":"30","city_name":"Patiala"},
    {"id":"500","state_id":"30","city_name":"Rupnagar"},
    {"id":"501","state_id":"30","city_name":"Mohali"},
    {"id":"502","state_id":"30","city_name":"Sangrur"},
    {"id":"503","state_id":"30","city_name":"Tarn Taran"},
    {"id":"504","state_id":"31","city_name":"Ajmer"},
    {"id":"505","state_id":"31","city_name":"Alwar"},
    {"id":"506","state_id":"31","city_name":"Banswara"},
    {"id":"507","state_id":"31","city_name":"Baran"},
    {"id":"508","state_id":"31","city_name":"Barmer"},
    {"id":"509","state_id":"31","city_name":"Bharatpur"},
    {"id":"510","state_id":"31","city_name":"Bhilwara"},
    {"id":"511","state_id":"31","city_name":"Bikaner"},
    {"id":"512","state_id":"31","city_name":"Bundi"},
    {"id":"513","state_id":"31","city_name":"Chittorgarh"},
    {"id":"514","state_id":"31","city_name":"Churu"},
    {"id":"515","state_id":"31","city_name":"Dausa"},
    {"id":"516","state_id":"31","city_name":"Dholpur"},
    {"id":"517","state_id":"31","city_name":"Dungarpur"},
    {"id":"518","state_id":"31","city_name":"Hanumangarh"},
    {"id":"519","state_id":"31","city_name":"Jaipur"},
    {"id":"520","state_id":"31","city_name":"Jaisalmer"},
    {"id":"521","state_id":"31","city_name":"Jalore"},
    {"id":"522","state_id":"31","city_name":"Jhalawar"},
    {"id":"523","state_id":"31","city_name":"Jhunjhunu"},
    {"id":"524","state_id":"31","city_name":"Jodhpur"},
    {"id":"525","state_id":"31","city_name":"Karauli"},
    {"id":"526","state_id":"31","city_name":"Kota"},
    {"id":"527","state_id":"31","city_name":"Nagaur"},
    {"id":"528","state_id":"31","city_name":"Pali"},
    {"id":"529","state_id":"31","city_name":"Pratapgarh"},
    {"id":"530","state_id":"31","city_name":"Rajsamand"},
    {"id":"531","state_id":"31","city_name":"Sawai Madhopur"},
    {"id":"532","state_id":"31","city_name":"Sikar"},
    {"id":"533","state_id":"31","city_name":"Sirohi"},
    {"id":"534","state_id":"31","city_name":"Sri Ganganagar"},
    {"id":"535","state_id":"31","city_name":"Tonk"},
    {"id":"536","state_id":"31","city_name":"Udaipur"},
    {"id":"537","state_id":"32","city_name":"East Sikkim"},
    {"id":"538","state_id":"32","city_name":"North Sikkim"},
    {"id":"539","state_id":"32","city_name":"South Sikkim"},
    {"id":"540","state_id":"32","city_name":"West Sikkim"},
    {"id":"541","state_id":"33","city_name":"Ariyalur"},
    {"id":"542","state_id":"33","city_name":"Chengalpattu"},
    {"id":"543","state_id":"33","city_name":"Chennai"},
    {"id":"544","state_id":"33","city_name":"Coimbatore"},
    {"id":"545","state_id":"33","city_name":"Cuddalore"},
    {"id":"546","state_id":"33","city_name":"Dharmapuri"},
    {"id":"547","state_id":"33","city_name":"Dindigul"},
    {"id":"548","state_id":"33","city_name":"Erode"},
    {"id":"549","state_id":"33","city_name":"Kallakurichi"},
    {"id":"550","state_id":"33","city_name":"Kanchipuram"},
    {"id":"551","state_id":"33","city_name":"Kanyakumari"},
    {"id":"552","state_id":"33","city_name":"Karur"},
    {"id":"553","state_id":"33","city_name":"Krishnagiri"},
    {"id":"554","state_id":"33","city_name":"Madurai"},
    {"id":"555","state_id":"33","city_name":"Nagapattinam"},
    {"id":"556","state_id":"33","city_name":"Namakkal"},
    {"id":"557","state_id":"33","city_name":"Nilgiris"},
    {"id":"558","state_id":"33","city_name":"Perambalur"},
    {"id":"559","state_id":"33","city_name":"Pudukkottai"},
    {"id":"560","state_id":"33","city_name":"Ramanathapuram"},
    {"id":"561","state_id":"33","city_name":"Ranipet"},
    {"id":"562","state_id":"33","city_name":"Salem"},
    {"id":"563","state_id":"33","city_name":"Sivaganga"},
    {"id":"564","state_id":"33","city_name":"Tenkasi"},
    {"id":"565","state_id":"33","city_name":"Thanjavur"},
    {"id":"566","state_id":"33","city_name":"Theni"},
    {"id":"567","state_id":"33","city_name":"Thoothukudi (Tuticorin)"},
    {"id":"568","state_id":"33","city_name":"Tiruchirappalli"},
    {"id":"569","state_id":"33","city_name":"Tirunelveli"},
    {"id":"570","state_id":"33","city_name":"Tirupathur"},
    {"id":"571","state_id":"33","city_name":"Tiruppur"},
    {"id":"572","state_id":"33","city_name":"Tiruvallur"},
    {"id":"573","state_id":"33","city_name":"Tiruvannamalai"},
    {"id":"574","state_id":"33","city_name":"Tiruvarur"},
    {"id":"575","state_id":"33","city_name":"Vellore"},
    {"id":"576","state_id":"33","city_name":"Viluppuram"},
    {"id":"577","state_id":"33","city_name":"Virudhunagar"},
    {"id":"578","state_id":"34","city_name":"Adilabad"},
    {"id":"579","state_id":"34","city_name":"Bhadradri Kothagudem"},
    {"id":"580","state_id":"34","city_name":"Hyderabad"},
    {"id":"581","state_id":"34","city_name":"Jagtial"},
    {"id":"582","state_id":"34","city_name":"Jangaon"},
    {"id":"583","state_id":"34","city_name":"Jayashankar Bhoopalpally"},
    {"id":"584","state_id":"34","city_name":"Jogulamba Gadwal"},
    {"id":"585","state_id":"34","city_name":"Kamareddy"},
    {"id":"586","state_id":"34","city_name":"Karimnagar"},
    {"id":"587","state_id":"34","city_name":"Khammam"},
    {"id":"588","state_id":"34","city_name":"Komaram Bheem Asifabad"},
    {"id":"589","state_id":"34","city_name":"Mahabubabad"},
    {"id":"590","state_id":"34","city_name":"Mahabubnagar"},
    {"id":"591","state_id":"34","city_name":"Mancherial"},
    {"id":"592","state_id":"34","city_name":"Medak"},
    {"id":"593","state_id":"34","city_name":"Medchal"},
    {"id":"594","state_id":"34","city_name":"Nagarkurnool"},
    {"id":"595","state_id":"34","city_name":"Nalgonda"},
    {"id":"596","state_id":"34","city_name":"Nirmal"},
    {"id":"597","state_id":"34","city_name":"Nizamabad"},
    {"id":"598","state_id":"34","city_name":"Peddapalli"},
    {"id":"599","state_id":"34","city_name":"Rajanna Sircilla"},
    {"id":"600","state_id":"34","city_name":"Rangareddy"},
    {"id":"601","state_id":"34","city_name":"Sangareddy"},
    {"id":"602","state_id":"34","city_name":"Siddipet"},
    {"id":"603","state_id":"34","city_name":"Suryapet"},
    {"id":"604","state_id":"34","city_name":"Vikarabad"},
    {"id":"605","state_id":"34","city_name":"Wanaparthy"},
    {"id":"606","state_id":"34","city_name":"Warangal (Rural)"},
    {"id":"607","state_id":"34","city_name":"Warangal (Urban)"},
    {"id":"608","state_id":"34","city_name":"Yadadri Bhuvanagiri"},
    {"id":"609","state_id":"35","city_name":"Dhalai"},
    {"id":"610","state_id":"35","city_name":"Gomati"},
    {"id":"611","state_id":"35","city_name":"Khowai"},
    {"id":"612","state_id":"35","city_name":"North Tripura"},
    {"id":"613","state_id":"35","city_name":"Sepahijala"},
    {"id":"614","state_id":"35","city_name":"South Tripura"},
    {"id":"615","state_id":"35","city_name":"Unakoti"},
    {"id":"616","state_id":"35","city_name":"West Tripura"},
    {"id":"617","state_id":"36","city_name":"Almora"},
    {"id":"618","state_id":"36","city_name":"Bageshwar"},
    {"id":"619","state_id":"36","city_name":"Chamoli"},
    {"id":"620","state_id":"36","city_name":"Champawat"},
    {"id":"621","state_id":"36","city_name":"Dehradun"},
    {"id":"622","state_id":"36","city_name":"Haridwar"},
    {"id":"623","state_id":"36","city_name":"Nainital"},
    {"id":"624","state_id":"36","city_name":"Pauri Garhwal"},
    {"id":"625","state_id":"36","city_name":"Pithoragarh"},
    {"id":"626","state_id":"36","city_name":"Rudraprayag"},
    {"id":"627","state_id":"36","city_name":"Tehri Garhwal"},
    {"id":"628","state_id":"36","city_name":"Udham Singh Nagar"},
    {"id":"629","state_id":"36","city_name":"Uttarkashi"},
    {"id":"630","state_id":"37","city_name":"Agra"},
    {"id":"631","state_id":"37","city_name":"Allahabad"},
    {"id":"632","state_id":"37","city_name":"Ambedkar Nagar"},
    {"id":"633","state_id":"37","city_name":"Amethi (Chatrapati Sahuji Mahraj Nagar)"},
    {"id":"634","state_id":"37","city_name":"Amroha (J.P. Nagar)"},
    {"id":"635","state_id":"37","city_name":"Auraiya"},
    {"id":"636","state_id":"37","city_name":"Azamgarh"},
    {"id":"637","state_id":"37","city_name":"Baghpat"},
    {"id":"638","state_id":"37","city_name":"Bahraich"},
    {"id":"639","state_id":"37","city_name":"Ballia"},
    {"id":"640","state_id":"37","city_name":"Balrampur"},
    {"id":"641","state_id":"37","city_name":"Banda"},
    {"id":"642","state_id":"37","city_name":"Barabanki"},
    {"id":"643","state_id":"37","city_name":"Bareilly"},
    {"id":"644","state_id":"37","city_name":"Basti"},
    {"id":"645","state_id":"37","city_name":"Bhadohi"},
    {"id":"646","state_id":"37","city_name":"Bijnor"},
    {"id":"647","state_id":"37","city_name":"Budaun"},
    {"id":"648","state_id":"37","city_name":"Bulandshahr"},
    {"id":"649","state_id":"37","city_name":"Chandauli"},
    {"id":"650","state_id":"37","city_name":"Chitrakoot"},
    {"id":"651","state_id":"37","city_name":"Deoria"},
    {"id":"652","state_id":"37","city_name":"Etah"},
    {"id":"653","state_id":"37","city_name":"Etawah"},
    {"id":"654","state_id":"37","city_name":"Faizabad"},
    {"id":"655","state_id":"37","city_name":"Farrukhabad"},
    {"id":"656","state_id":"37","city_name":"Fatehpur"},
    {"id":"657","state_id":"37","city_name":"Firozabad"},
    {"id":"658","state_id":"37","city_name":"Gautam Buddha Nagar"},
    {"id":"659","state_id":"37","city_name":"Ghaziabad"},
    {"id":"660","state_id":"37","city_name":"Ghazipur"},
    {"id":"661","state_id":"37","city_name":"Gonda"},
    {"id":"662","state_id":"37","city_name":"Gorakhpur"},
    {"id":"663","state_id":"37","city_name":"Hamirpur"},
    {"id":"664","state_id":"37","city_name":"Hapur (Panchsheel Nagar)"},
    {"id":"665","state_id":"37","city_name":"Hardoi"},
    {"id":"666","state_id":"37","city_name":"Hathras"},
    {"id":"667","state_id":"37","city_name":"Jalaun"},
    {"id":"668","state_id":"37","city_name":"Jaunpur"},
    {"id":"669","state_id":"37","city_name":"Jhansi"},
    {"id":"670","state_id":"37","city_name":"Kannauj"},
    {"id":"671","state_id":"37","city_name":"Kanpur Dehat"},
    {"id":"672","state_id":"37","city_name":"Kanpur Nagar"},
    {"id":"673","state_id":"37","city_name":"Kanshiram Nagar (Kasganj)"},
    {"id":"674","state_id":"37","city_name":"Kaushambi"},
    {"id":"675","state_id":"37","city_name":"Kushinagar (Padrauna)"},
    {"id":"676","state_id":"37","city_name":"Lakhimpur - Kheri"},
    {"id":"677","state_id":"37","city_name":"Lalitpur"},
    {"id":"678","state_id":"37","city_name":"Lucknow"},
    {"id":"679","state_id":"37","city_name":"Maharajganj"},
    {"id":"680","state_id":"37","city_name":"Mahoba"},
    {"id":"681","state_id":"37","city_name":"Mainpuri"},
    {"id":"682","state_id":"37","city_name":"Mathura"},
    {"id":"683","state_id":"37","city_name":"Mau"},
    {"id":"684","state_id":"37","city_name":"Meerut"},
    {"id":"685","state_id":"37","city_name":"Mirzapur"},
    {"id":"686","state_id":"37","city_name":"Moradabad"},
    {"id":"687","state_id":"37","city_name":"Muzaffarnagar"},
    {"id":"688","state_id":"37","city_name":"Pilibhit"},
    {"id":"689","state_id":"37","city_name":"Pratapgarh"},
    {"id":"690","state_id":"37","city_name":"Prayagraj(Aligarh)"},
    {"id":"691","state_id":"37","city_name":"RaeBareli"},
    {"id":"692","state_id":"37","city_name":"Rampur"},
    {"id":"693","state_id":"37","city_name":"Saharanpur"},
    {"id":"694","state_id":"37","city_name":"Sambhal (Bhim Nagar)"},
    {"id":"695","state_id":"37","city_name":"Sant Kabir Nagar"},
    {"id":"696","state_id":"37","city_name":"Shahjahanpur"},
    {"id":"697","state_id":"37","city_name":"Shamali (Prabuddh Nagar)"},
    {"id":"698","state_id":"37","city_name":"Shravasti"},
    {"id":"699","state_id":"37","city_name":"Siddharth Nagar"},
    {"id":"700","state_id":"37","city_name":"Sitapur"},
    {"id":"701","state_id":"37","city_name":"Sonbhadra"},
    {"id":"702","state_id":"37","city_name":"Sultanpur"},
    {"id":"703","state_id":"37","city_name":"Unnao"},
    {"id":"704","state_id":"37","city_name":"Varanasi"},
    {"id":"705","state_id":"38","city_name":"Alipurduar"},
    {"id":"706","state_id":"38","city_name":"Bankura"},
    {"id":"707","state_id":"38","city_name":"Birbhum"},
    {"id":"708","state_id":"38","city_name":"Cooch Behar"},
    {"id":"709","state_id":"38","city_name":"Dakshin Dinajpur (South Dinajpur)"},
    {"id":"710","state_id":"38","city_name":"Darjeeling"},
    {"id":"711","state_id":"38","city_name":"Hooghly"},
    {"id":"712","state_id":"38","city_name":"Howrah"},
    {"id":"713","state_id":"38","city_name":"Jalpaiguri"},
    {"id":"714","state_id":"38","city_name":"Jhargram"},
    {"id":"715","state_id":"38","city_name":"Kalimpong"},
    {"id":"716","state_id":"38","city_name":"Kolkata"},
    {"id":"717","state_id":"38","city_name":"Malda"},
    {"id":"718","state_id":"38","city_name":"Murshidabad"},
    {"id":"719","state_id":"38","city_name":"Nadia"},
    {"id":"720","state_id":"38","city_name":"North 24 Parganas"},
    {"id":"721","state_id":"38","city_name":"Paschim Medinipur (West Medinipur)"},
    {"id":"722","state_id":"38","city_name":"Paschim (West) Burdwan (Bardhaman)"},
    {"id":"723","state_id":"38","city_name":"Purba Burdwan (Bardhaman)"},
    {"id":"724","state_id":"38","city_name":"Purba Medinipur (East Medinipur)"},
    {"id":"725","state_id":"38","city_name":"Purulia"},
    {"id":"726","state_id":"38","city_name":"South 24 Parganas"},
    {"id":"727","state_id":"38","city_name":"Uttar Dinajpur (North Dinajpur)"}
    ]
   
    