
export const stateList = [
    {"id":"2","name":"Andaman And Nicobar Islands"},
    {"id":"3","name":"Andhra Pradesh"},
    {"id":"4","name":"Arunachal Pradesh"},
    {"id":"5","name":"Assam"},
    {"id":"6","name":"Bihar"},
    {"id":"7","name":"Chandigarh (UT)"},
    {"id":"8","name":"Chhattisgarh"},
    {"id":"9","name":"The Dadra And Nagar Haveli And Daman And Diu"},
    {"id":"10","name":"West Bengal"},
    {"id":"11","name":"Delhi"},
    {"id":"12","name":"Goa"},
    {"id":"13","name":"Gujarat"},
    {"id":"14","name":"Haryana"},
    {"id":"15","name":"Himachal Pradesh"},
    {"id":"16","name":"Jammu And Kashmir"},
    {"id":"17","name":"Jharkhand"},
    {"id":"18","name":"Karnataka"},
    {"id":"19","name":"Kerala"},
    {"id":"20","name":"Ladakh"},
    {"id":"21","name":"Lakshadweep"},
    {"id":"22","name":"Madhya Pradesh"},
    {"id":"23","name":"Maharashtra"},
    {"id":"24","name":"Manipur"},
    {"id":"25","name":"Meghalaya"},
    {"id":"26","name":"Mizoram"},
    {"id":"27","name":"Nagaland"},
    {"id":"28","name":"Odisha"},
    {"id":"29","name":"Puducherry (UT)"},
    {"id":"30","name":"Punjab"},
    {"id":"31","name":"Rajasthan"},
    {"id":"32","name":"Sikkim"},
    {"id":"33","name":"Tamil Nadu"},
    {"id":"34","name":"Telangana"},
    {"id":"35","name":"Tripura"},
    {"id":"36","name":"Uttarakhand"},
    {"id":"37","name":"Uttar Pradesh"},
    
    ]
    
    